import TheHive from "./Assets/Projects/theHive.PNG";
import TheIsomer from "./Assets/Projects/isomer.png";
import TheLeadGen from "./Assets/Projects/leadGen.png";



export const PROJECTS = [
  {
    image: TheHive,
    name: "The Hive",
    technologyUsed: "ReactJs, Javascript, Redux, MaterialUI, Google Map Api",
    description:  "The HiVE is a location-centric SaaS application. The HiVE enables users to identify via geolocation where cleaning services are being performed. From finding and viewing these Geo Locations, using Google maps, more information about the Client, the staff, the services associated with the location is made viewable in The Hive. Here, I was working as a frontend developer on ReactJS where I worked on Google Map API and Libraries such as MaterialUI and Google Sign in, along with that all code merging and pushing to code to client repo as well. This project is mainly focused on Google Maps. I have also worked on the Account tab, Services tab, and authentication. It was my first time working onGoogle Maps and I learned a lot from the execution.",
    url: " ",
  },
  {
    image: TheIsomer,
    name: "Isomer.Ai",
    technologyUsed: "JavaScript, ReactJS, MaterialUI, Recharts, ReactFormik, Redux",
    description: "Basetwo is an industrial AI platform for biopharma manufacturers. The platform enables customers to build and deploy AI pipelines* in a studio “drag and drop” environment. Typical pipeline operations include importing data (i.e. Excel/csv), cleaning data, training an ML model and pushing model results to a 3rd party system. Once a pipeline is deployed, it is operational and the user can view live results from the pipeline.",
    url: " ",
  },
  {
    image: TheLeadGen,
    name: "LeadgenAutomation",
    technologyUsed: "ReactJS, Javascript, Redux, MaterialUI, MomentJS, FireBase",
    description: "LeadgenAutomation is a company own managed Web Application, where founder and ceo can keep track of all the project (associated with the leading project managers) running inside the company. Keep track of deadline and status of project. Role based permission and lead generated by all project manager.",
    url: " ",
  },
  // {
  //   image: AUTOMATION,
  //   name: "3automation.com (RPA)",
  //   technologyUsed: "ReactJs, Typescript, Redux",
  //   description: "The next-gen Robotic Process Automation (#RPA) platform for retail and telecom domains. The ultimate automation platform for your Shopify, Email, E- commerce shop",
  //   url: "https://www.3automation.com/",
  // },
  // {
  //   image: GUAMEDIA,
  //   name: "GuaMedia",
  //   technologyUsed: "ReactNative, Javascript, Redux",
  //   description: "Social media mobile app similar to Twitter for china. Social networking GUOMEDIA is an all-in-one social networking platform where users can build their own user profiles, create their own posts, Livestream broadcast and follow each other",
  //   url: "https://play.google.com/store/apps/details?id=com.tiu.guo.media",
  // },
];

export const SKILLS = [
  { name: "ReactJs", initialRating: 4.5 },
 // { name: "React-Native", initialRating: 4 },
  { name: "JavaScript", initialRating: 4.5 },
  { name: "Redux", initialRating: 4 },
 // { name: "Shopify/Reactjs", initialRating: 4 },
  { name: "Nodejs", initialRating: 3 },
  { name: "MongoDB", initialRating: 3 },
  { name: "Html", initialRating: 4.5 },
  { name: "CSS", initialRating: 4.5 },
//  { name: "Unit-Testing(Jest)", initialRating: 3 },
  { name: "TypeScript", initialRating: 3 },
 // { name: "Graphql", initialRating: 4 },
 // { name: "Apollo", initialRating: 4 },
  { name: "AntD | ReactStrap | Material UI", initialRating: 4 },
 // { name: "Shopify Polaris", initialRating: 4 },
  { name: "Git", initialRating: 4 },
];

export const TOOLS = ["Visual Studio Code", "Git", "Chrome DevTools", "Npm (Node Package Manager)", "Sublime Text", "Heroku", "Postman"]
