import TheHive from "./Assets/Projects/theHive.PNG";
import TheIsomer from "./Assets/Projects/isomer.png";
import TheLeadGen from "./Assets/Projects/leadGen.png";
import TheIsonBot from "./Assets/Projects/isonBot.png";
import TaskManagement from "./Assets/Projects/taskManagement.png";

export const PROJECTS = [
  {
    image: TheIsonBot,
    name: "Ison Ai Bot",
    technologyUsed:
      "ReactJs, Typescript, Redux, Node Js, Express Js, ChatGPT, Redux Saga",
    description:
      "Ison AI Bot is a conversational AI chat bot that is made for the BPO industry to maximise their revenue. In this bot, we have used ChatGPT to train the uploaded document from the web and mobile. It consists of multiple unique features, like training the bot within the context, setting the response rate, tracking the record of every chat, restricting the maximum upload of documents, and many more. I have worked on the authentication part, like Login/Signup, Chat Screen, BotTrain, BotRetrain, BotConfiguration, e.t.c.",
    url: "",
  },
  {
    image: TheHive,
    name: "The Hive",
    technologyUsed: "ReactJs, Javascript, Redux, MaterialUI, Google Map Api",
    description:
      "The HiVE is a location-centric SaaS application. The HiVE enables users to identify via geolocation where cleaning services are being performed. From finding and viewing these Geo Locations, using Google maps, more information about the Client, the staff, the services associated with the location is made viewable in The Hive. Here, I was working as a frontend developer on ReactJS where I worked on Google Map API and Libraries such as MaterialUI and Google Sign in, along with that all code merging and pushing to code to client repo as well. This project is mainly focused on Google Maps. I have also worked on the Account tab, Services tab, and authentication. It was my first time working onGoogle Maps and I learned a lot from the execution.",
    url: " ",
  },
  {
    image: TheIsomer,
    name: "Isomer.Ai",
    technologyUsed:
      "JavaScript, ReactJS, MaterialUI, Recharts, ReactFormik, Redux",
    description:
      "Basetwo is an industrial AI platform for biopharma manufacturers. The platform enables customers to build and deploy AI pipelines* in a studio “drag and drop” environment. Typical pipeline operations include importing data (i.e. Excel/csv), cleaning data, training an ML model and pushing model results to a 3rd party system. Once a pipeline is deployed, it is operational and the user can view live results from the pipeline.",
    url: " ",
  },
  {
    image: TheLeadGen,
    name: "LeadgenAutomation",
    technologyUsed:
      "ReactJS, Javascript, Redux, MaterialUI, MomentJS, FireBase",
    description:
      "LeadgenAutomation is a company own managed Web Application, where founder and ceo can keep track of all the project (associated with the leading project managers) running inside the company. Keep track of deadline and status of project. Role based permission and lead generated by all project manager.",
    url: " ",
  },

  {
    image: TaskManagement,
    name: "Task Management",
    technologyUsed: "React Js, Javascript, Redux, Node JS, Express JS, MongoDB",
    description:
      "The Task Management MERN App is a full-stack web application enabling users to create, edit, delete, search, and filter tasks by status (completed or pending). Built using MongoDB, Express.js, React, and Node.js, it features secure user authentication with JWT, a responsive interface styled with Material-UI, and a robust backend API for efficient task and user management. The application ensures smooth performance and scalability, making it suitable for personal and professional use. Its modern design and user-centric features provide an intuitive experience for managing tasks effectively.",
    url: "",
  },
];

export const SKILLS = [
  { name: "ReactJs", initialRating: 4.5 },
  { name: "Next JS", initialRating: 4 },
  { name: "JavaScript", initialRating: 4.5 },
  { name: "Redux", initialRating: 4 },
  { name: "Nodejs", initialRating: 4 },
  { name: "MongoDB", initialRating: 4 },
  { name: "Html", initialRating: 4.5 },
  { name: "CSS", initialRating: 4.5 },
  { name: "TypeScript", initialRating: 4 },
  { name: "AntD | ReactStrap | Material UI", initialRating: 4 },
  { name: "Git | Bitbucket", initialRating: 4.5 },
];

export const TOOLS = [
  "Visual Studio Code",
  "Git",
  "Chrome DevTools",
  "Npm (Node Package Manager)",
  "Sublime Text",
  "Heroku",
  "Postman",
];
